server:
  port: 8080
spring:
  application:
    name: "reports"
  devtools:
    add-properties: false
  profiles:
    include: null

aws:
  dynamodb:
    region: "us-east-1"

entrypoint:
  sqs:
    region: "us-east-1"
    queueUrl: "https://sqs.us-east-1.amazonaws.com/119694354572/reports-listener"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
