server:
  servlet:
    context-path: /reports
  port: 8082
aws:
  ses:
    region: us-east-1
  dynamodb:
    region: us-east-1
    tables:
      approved-reports: approved_reports
      reports: reports

entrypoint:
  sqs:
    region: "us-east-1"
    queueUrlUpdateReport: "https://sqs.us-east-1.amazonaws.com/119694354572/reports-listener"
    queueUrlDailyReport: "https://sqs.us-east-1.amazonaws.com/119694354572/daily-report"

security:
  jwt:
    public-key-location: ${JWT_PUBLIC_KEY}

report:
  email:
    source: georffreyarevalo@gmail.com
    destination: georffrey10@gmail.com