server:
  port: ${PORT}
spring:
  config:
    import: ${AWS_NAME_SECRET_MANAGER}

aws:
  ses:
    region: ${DAILY_REPORT_SQS_REGION}
  dynamodb:
    region: ${AWS_REGION_DYNAMO}
    tables:
      approved-reports: ${TABLE_APPROVED_REPORTS}
      reports: ${TABLE_REPORTS}

entrypoint:
  sqs:
    region: ${AWS_REGION_SQS_LISTER}
    queueUrlUpdateReport: ${URL_QUEUE_LISTENER}
    queueUrlDailyReport: ${URL_QUEUE_DAILY_REPORT}

security:
  jwt:
    public-key-location: ${JWT_PUBLIC_KEY}

report:
  email:
    source: ${EMAIL_SOURCE_DAILY_REPORT}
    destination: ${EMAIL_DESTINATION_DAILY_REPORT}