server:
  servlet:
    context-path: /reports
  port: 8082
aws:
  dynamodb:
    region: "us-east-1"

entrypoint:
  sqs:
    region: "us-east-1"
    queueUrl: "https://sqs.us-east-1.amazonaws.com/119694354572/reports-listener"

security:
  jwt:
    public-key-location: ${JWT_PUBLIC_KEY}