server:
  port: 8082
spring:
  application:
    name: "reports"
  devtools:
    add-properties: false
  profiles:
    active: "${PROFILE:dev}"
    include: null

entrypoint:
  sqs:
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
