server:
  port: ${PORT}
spring:
  config:
    import: ${AWS_NAME_SECRET_MANAGER}

aws:
  dynamodb:
    region: ${AWS_REGION_DYNAMO}
    tables:
      approved-reports: ${TABLE_APPROVED_REPORTS}
      reports: ${TABLE_REPORTS}

entrypoint:
  sqs:
    region: ${AWS_REGION_SQS_LISTER}
    queueUrl: ${URL_QUEUE_LISTENER}

security:
  jwt:
    public-key-location: ${JWT_PUBLIC_KEY}