spring:
  application:
    name: "reports"
  devtools:
    add-properties: false
  profiles:
    active: "${PROFILE:dev}"
    include: null
entrypoint:
  sqs:
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
management:
  endpoints:
    web:
      base-path: /reports/actuator
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

springdoc:
  swagger-ui:
    path: /reports/openapi/swagger-ui
  api-docs:
    path: /reports/openapi/v3/api-docs
  packages-to-scan:
    - co.com.crediya
  paths-to-match:
    - /**

routes:
  paths:
    reports: "/reports/api/v1/reports"
